version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - ./uploads:/usr/src/app/uploads
      - ./hls:/usr/src/app/hls
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s