version: '3.8'

services:
  app:
    build: .
    expose:
      - "${PORT}:4000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - ./uploads:/usr/src/app/uploads
      - ./hls:/usr/src/app/hls
    restart: unless-stopped
    stop_grace_period: 30s  # Give container time to shutdown gracefully
    init: true             # Use tini for proper signal handling
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge